// Code generated by protoc-gen-go. DO NOT EDIT.
// source: invoice.proto

/*
Package invoice is a generated protocol buffer package.

It is generated from these files:
	invoice.proto

It has these top-level messages:
	InvoiceData
	InvoiceDataSalts
	InvoiceDocument
*/
package invoice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import coredocument "github.com/CentrifugeInc/centrifuge-protobufs/coredocument"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// InvoiceData is the default invoice schema
type InvoiceData struct {
	Country     string                     `protobuf:"bytes,2,opt,name=country" json:"country,omitempty"`
	Currency    string                     `protobuf:"bytes,3,opt,name=currency" json:"currency,omitempty"`
	Amount      int64                      `protobuf:"varint,4,opt,name=amount" json:"amount,omitempty"`
	Recipient   []byte                     `protobuf:"bytes,5,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Sender      []byte                     `protobuf:"bytes,6,opt,name=sender,proto3" json:"sender,omitempty"`
	Payee       []byte                     `protobuf:"bytes,7,opt,name=payee,proto3" json:"payee,omitempty"`
	Comment     string                     `protobuf:"bytes,8,opt,name=comment" json:"comment,omitempty"`
	DueDate     *google_protobuf.Timestamp `protobuf:"bytes,9,opt,name=due_date,json=dueDate" json:"due_date,omitempty"`
	DateCreated *google_protobuf.Timestamp `protobuf:"bytes,11,opt,name=date_created,json=dateCreated" json:"date_created,omitempty"`
}

func (m *InvoiceData) Reset()                    { *m = InvoiceData{} }
func (m *InvoiceData) String() string            { return proto.CompactTextString(m) }
func (*InvoiceData) ProtoMessage()               {}
func (*InvoiceData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *InvoiceData) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *InvoiceData) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *InvoiceData) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *InvoiceData) GetRecipient() []byte {
	if m != nil {
		return m.Recipient
	}
	return nil
}

func (m *InvoiceData) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *InvoiceData) GetPayee() []byte {
	if m != nil {
		return m.Payee
	}
	return nil
}

func (m *InvoiceData) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *InvoiceData) GetDueDate() *google_protobuf.Timestamp {
	if m != nil {
		return m.DueDate
	}
	return nil
}

func (m *InvoiceData) GetDateCreated() *google_protobuf.Timestamp {
	if m != nil {
		return m.DateCreated
	}
	return nil
}

type InvoiceDataSalts struct {
	Country     []byte `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	Currency    []byte `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount      []byte `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Recipient   []byte `protobuf:"bytes,5,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Sender      []byte `protobuf:"bytes,6,opt,name=sender,proto3" json:"sender,omitempty"`
	Payee       []byte `protobuf:"bytes,7,opt,name=payee,proto3" json:"payee,omitempty"`
	Comment     []byte `protobuf:"bytes,8,opt,name=comment,proto3" json:"comment,omitempty"`
	DueDate     []byte `protobuf:"bytes,9,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	DateCreated []byte `protobuf:"bytes,11,opt,name=date_created,json=dateCreated,proto3" json:"date_created,omitempty"`
}

func (m *InvoiceDataSalts) Reset()                    { *m = InvoiceDataSalts{} }
func (m *InvoiceDataSalts) String() string            { return proto.CompactTextString(m) }
func (*InvoiceDataSalts) ProtoMessage()               {}
func (*InvoiceDataSalts) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *InvoiceDataSalts) GetCountry() []byte {
	if m != nil {
		return m.Country
	}
	return nil
}

func (m *InvoiceDataSalts) GetCurrency() []byte {
	if m != nil {
		return m.Currency
	}
	return nil
}

func (m *InvoiceDataSalts) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *InvoiceDataSalts) GetRecipient() []byte {
	if m != nil {
		return m.Recipient
	}
	return nil
}

func (m *InvoiceDataSalts) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *InvoiceDataSalts) GetPayee() []byte {
	if m != nil {
		return m.Payee
	}
	return nil
}

func (m *InvoiceDataSalts) GetComment() []byte {
	if m != nil {
		return m.Comment
	}
	return nil
}

func (m *InvoiceDataSalts) GetDueDate() []byte {
	if m != nil {
		return m.DueDate
	}
	return nil
}

func (m *InvoiceDataSalts) GetDateCreated() []byte {
	if m != nil {
		return m.DateCreated
	}
	return nil
}

type InvoiceDocument struct {
	CoreDocument *coredocument.CoreDocument `protobuf:"bytes,1,opt,name=core_document,json=coreDocument" json:"core_document,omitempty"`
	Data         *InvoiceData               `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	Salts        *InvoiceDataSalts          `protobuf:"bytes,3,opt,name=salts" json:"salts,omitempty"`
}

func (m *InvoiceDocument) Reset()                    { *m = InvoiceDocument{} }
func (m *InvoiceDocument) String() string            { return proto.CompactTextString(m) }
func (*InvoiceDocument) ProtoMessage()               {}
func (*InvoiceDocument) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *InvoiceDocument) GetCoreDocument() *coredocument.CoreDocument {
	if m != nil {
		return m.CoreDocument
	}
	return nil
}

func (m *InvoiceDocument) GetData() *InvoiceData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *InvoiceDocument) GetSalts() *InvoiceDataSalts {
	if m != nil {
		return m.Salts
	}
	return nil
}

func init() {
	proto.RegisterType((*InvoiceData)(nil), "invoice.InvoiceData")
	proto.RegisterType((*InvoiceDataSalts)(nil), "invoice.InvoiceDataSalts")
	proto.RegisterType((*InvoiceDocument)(nil), "invoice.InvoiceDocument")
}

func init() { proto.RegisterFile("invoice.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x93, 0x4f, 0x8f, 0xd3, 0x30,
	0x10, 0xc5, 0x95, 0xee, 0xb6, 0x69, 0x1d, 0xaf, 0x40, 0xd6, 0x0a, 0x79, 0x23, 0x24, 0xc2, 0x9e,
	0x72, 0x21, 0x91, 0x0a, 0x2b, 0x4e, 0x08, 0x89, 0x72, 0xd9, 0x6b, 0xe0, 0xc4, 0xa5, 0x72, 0x9d,
	0xd9, 0x10, 0x69, 0x63, 0x47, 0x8e, 0x8d, 0xd4, 0x3b, 0x5f, 0x87, 0x33, 0x5f, 0x0f, 0xd9, 0x8e,
	0xfb, 0x67, 0xd5, 0x8a, 0xdb, 0x1e, 0xdf, 0xcc, 0x7b, 0xc9, 0xe4, 0x97, 0x19, 0x74, 0xd5, 0x8a,
	0x5f, 0xb2, 0xe5, 0x50, 0xf4, 0x4a, 0x6a, 0x49, 0xe2, 0x51, 0xa6, 0x6f, 0x1a, 0x29, 0x9b, 0x47,
	0x28, 0x5d, 0x79, 0x63, 0x1e, 0x4a, 0xdd, 0x76, 0x30, 0x68, 0xd6, 0xf5, 0xde, 0x99, 0x7e, 0xe0,
	0x20, 0xb4, 0x6a, 0x1f, 0x4c, 0x03, 0xef, 0x82, 0x69, 0x28, 0xb9, 0x54, 0x50, 0x4b, 0x6e, 0x3a,
	0x10, 0xfa, 0x48, 0xf8, 0xd4, 0xed, 0xdf, 0x09, 0x4a, 0xee, 0xfd, 0x2b, 0xbe, 0x32, 0xcd, 0x08,
	0x45, 0x31, 0x97, 0x46, 0x68, 0xb5, 0xa5, 0x93, 0x2c, 0xca, 0x17, 0x55, 0x90, 0x24, 0x45, 0x73,
	0x6e, 0x94, 0x02, 0xc1, 0xb7, 0xf4, 0xc2, 0xb5, 0x76, 0x9a, 0xbc, 0x42, 0x33, 0xd6, 0x59, 0x1f,
	0xbd, 0xcc, 0xa2, 0xfc, 0xa2, 0x1a, 0x15, 0x79, 0x8d, 0x16, 0x0a, 0x78, 0xdb, 0xb7, 0x20, 0x34,
	0x9d, 0x66, 0x51, 0x8e, 0xab, 0x7d, 0xc1, 0xa6, 0x06, 0x10, 0x35, 0x28, 0x3a, 0x73, 0xad, 0x51,
	0x91, 0x6b, 0x34, 0xed, 0xd9, 0x16, 0x80, 0xc6, 0xae, 0xec, 0x85, 0x9f, 0xac, 0xb3, 0xa3, 0xd3,
	0x79, 0x98, 0xcc, 0x49, 0x72, 0x87, 0xe6, 0xb5, 0x81, 0x75, 0xcd, 0x34, 0xd0, 0x45, 0x16, 0xe5,
	0xc9, 0x32, 0x2d, 0x3c, 0xad, 0x22, 0x80, 0x28, 0xbe, 0x07, 0x5a, 0x55, 0x5c, 0x1b, 0xfb, 0xa9,
	0x40, 0x3e, 0x21, 0x6c, 0x23, 0x6b, 0xae, 0x80, 0x69, 0xa8, 0x69, 0xf2, 0xdf, 0x68, 0x62, 0xfd,
	0x2b, 0x6f, 0xbf, 0xfd, 0x3d, 0x41, 0x2f, 0x0f, 0xc8, 0x7d, 0x63, 0x8f, 0x7a, 0x78, 0x8a, 0x0f,
	0x9f, 0xc7, 0x87, 0xcf, 0xe2, 0xc3, 0xcf, 0x81, 0x0f, 0xef, 0xf1, 0xdd, 0x3c, 0xc1, 0x87, 0xf7,
	0x88, 0xde, 0x9e, 0x40, 0x84, 0x8f, 0x31, 0xfc, 0x89, 0xd0, 0x8b, 0x80, 0x61, 0x5c, 0x2d, 0xf2,
	0x19, 0x5d, 0xd9, 0x55, 0x5b, 0x87, 0x5d, 0xa3, 0xd1, 0x88, 0xf6, 0x68, 0x01, 0x57, 0x52, 0xed,
	0x22, 0x15, 0xe6, 0x07, 0x8a, 0xe4, 0xe8, 0xb2, 0x66, 0x9a, 0x39, 0x86, 0xc9, 0xf2, 0xba, 0x08,
	0x37, 0x71, 0xc0, 0xbb, 0x72, 0x0e, 0x52, 0xa2, 0xe9, 0x60, 0xc9, 0x3b, 0xa6, 0xc9, 0xf2, 0xe6,
	0x94, 0xd5, 0xfd, 0x9a, 0xca, 0xfb, 0xbe, 0x7c, 0xfc, 0x71, 0xd7, 0xb4, 0xfa, 0xa7, 0xd9, 0x14,
	0x5c, 0x76, 0xe5, 0x6a, 0x77, 0x33, 0xf7, 0x82, 0x97, 0x27, 0x2f, 0x68, 0x7c, 0xe0, 0x66, 0xe6,
	0x4a, 0xef, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x04, 0x09, 0xb8, 0x2a, 0xa1, 0x03, 0x00, 0x00,
}
